(function(){
'use strict';
var token=document.body.dataset.token,lang=localStorage.getItem('afs_lang')||navigator.language.slice(0,2).toLowerCase(),currentFolder=null,data=null;
var names={ru:'Русский',en:'English',de:'Deutsch',uk:'Українська',ko:'한국어',zh:'简体中文',ja:'日本語',fr:'Français',pl:'Polski',tr:'Türkçe'};
if(!window.AFLocales[lang])lang='en';
function q(s){return document.querySelector(s)}
function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function t(k){var d=window.AFLocales[lang]||window.AFLocales.en;return d[k]||window.AFLocales.en[k]||k}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fmtBytes(n){n=Number(n)||0;if(n<1024)return n+' B';var u=['KiB','MiB','GiB','TiB','PiB'],i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(n>=100?0:n>=10?1:2)+' '+u[i]}
function toast(text,error){var el=q('#toast');el.textContent=text;el.className='toast'+(error?' error':'');clearTimeout(el._timer);el._timer=setTimeout(function(){el.className='toast hidden'},3500)}
function applyLanguage(){document.documentElement.lang=lang;qa('[data-l]').forEach(function(el){el.textContent=t(el.dataset.l)});render()}
function bindBrandImage(){var img=q('.brand-image');if(!img)return;var span=img.parentNode.querySelector('span');img.onload=function(){img.style.display='block';if(span)span.style.display='none'};img.onerror=function(){img.style.display='none';if(span)span.style.display='block'}}
function fillLanguages(){var el=q('#shareLanguage');el.innerHTML='';Object.keys(names).forEach(function(k){var o=document.createElement('option');o.value=k;o.textContent=names[k];el.appendChild(o)});el.value=lang;el.onchange=function(){lang=this.value;localStorage.setItem('afs_lang',lang);applyLanguage()}}
async function getInfo(){var url='/d/'+encodeURIComponent(token)+'/info'+(currentFolder?'?folder='+encodeURIComponent(currentFolder):'');var r=await fetch(url);if(!r.ok){showNotFound();return}var j=await r.json();if(j.needsPassword){showPassword();return}data=j.data;render()}
function showPassword(){q('#shareCard').innerHTML='<div class="share-file"><div class="share-icon">🔒</div><div class="share-name">'+t('protectedLink')+'</div><div class="field" style="max-width:360px;margin:20px auto"><label>'+t('enterPassword')+'</label><input id="sharePassword" type="password"></div><button id="openProtected" class="btn primary">'+t('openLink')+'</button><div id="passwordError" class="error-text"></div></div>';q('#openProtected').onclick=authPassword;q('#sharePassword').addEventListener('keydown',function(e){if(e.key==='Enter')authPassword()})}
async function authPassword(){var r=await fetch('/d/'+encodeURIComponent(token)+'/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:q('#sharePassword').value})});if(!r.ok){q('#passwordError').textContent=t('invalidSharePassword');return}await getInfo()}
function showNotFound(){q('#shareCard').innerHTML='<div class="share-file"><div class="share-icon">404</div><div class="share-name">'+t('notFound')+'</div></div>'}
function render(){if(!data)return;if(data.type==='file'){var thumb=data.thumbnail?'<img src="'+esc(data.thumbnail)+'" alt="">':'📄';q('#shareCard').innerHTML='<div class="share-file"><div class="share-icon">'+thumb+'</div><div class="share-name">'+esc(data.name)+'</div><div class="share-meta">'+fmtBytes(data.size)+' · ↓ '+esc(data.downloads||0)+'</div><a class="btn primary" download href="/d/'+encodeURIComponent(token)+'/download">'+t('download')+'</a></div>';return}var html='<div class="share-folder-head"><div><div class="share-name">📁 '+esc(data.currentName||data.name)+'</div><div class="share-meta">'+(data.files.length+data.folders.length)+' '+t('items')+'</div></div><div class="row-actions">'+(data.parentId?'<button id="folderBack" class="btn soft">← '+t('back')+'</button>':'')+'<a class="btn primary" download href="/d/'+encodeURIComponent(token)+'/download">'+t('downloadAll')+'</a></div></div><div class="table-list">';data.folders.forEach(function(f){html+='<div class="table-row share-folder" data-id="'+esc(f.Id||f.id)+'"><div><strong>📁 '+esc(f.Name||f.name)+'</strong></div><div></div><div></div><div><button class="small-btn open-folder">'+t('open')+'</button></div></div>'});data.files.forEach(function(f){html+='<div class="table-row"><div><strong>'+esc(f.name)+'</strong></div><div>'+fmtBytes(f.size)+'</div><div>↓ '+esc(f.downloads||0)+'</div><div><a class="small-btn" download style="text-decoration:none" href="/d/'+encodeURIComponent(token)+'/file/'+encodeURIComponent(f.Id||f.id)+'">'+t('download')+'</a></div></div>'});html+='</div>';q('#shareCard').innerHTML=html;qa('.open-folder').forEach(function(b){b.onclick=function(){currentFolder=b.closest('[data-id]').dataset.id;getInfo()}});var back=q('#folderBack');if(back)back.onclick=function(){currentFolder=data.parentId;getInfo()}}
bindBrandImage();fillLanguages();applyLanguage();getInfo().catch(function(e){toast(e.message,true);showNotFound()});
})();
